### ISSUE TITLE
XYZ Iterator panics when z_min >= (z_max - z_min)

### ISSUE THREAD

**Issue by jcmnn** [pka/tile-grid#2]
Changing this

https://github.com/pka/tile-grid/blob/9d279bd5db9ce811abb4d7591605b1a00d6f0817/src/tms_iterator.rs#L24

to

```rust
let limit = limits.first().unwrap();
```

fixes the bug.

**Comment by pka** [comment]
Fixed in #3. Thanks for reporting!
